### ISSUE TITLE
C4 and Cb4 are not 11 semitones apart.

### ISSUE THREAD

**Issue by PQKelly** [AudioKit/Tonic#16]
### Description

"Accidentals applied to a note do not have an effect on its ASPN number. For example, B♯3 and C4 have different octave numbers despite being enharmonically equivalent, because the B♯ is still considered part of the lower octave."

https://viva.pressbooks.pub/openmusictheory/chapter/aspn/

### Proposed Solution

Not sure how this assumption affects the rest of your calculations, but C4 and Cb4 are not 11 semitones apart.

### Describe Alternatives You've Considered

There are no alternative facts or alternative schools of thought about the octave designations of pitches.

**Comment by aure** [comment]
Thank you for pointing this out, it has been resolved.
