### ISSUE TITLE
shiftUp by an octave

### ISSUE THREAD

**Issue by Ei9il** [AudioKit/Tonic#30]
### Description

shiftUp only works with intervals but octave is not part of intervals

### Proposed Solution

include octave in intervals

### Describe Alternatives You've Considered

create additional function to shiftUpBySemitones(12)

**Comment by aure** [comment]
I initially thought this was a silly case, but it was so easy to implement so I did so. But, thanks to that it exposed a bug in our  `Interval.betweenNotes` function, so thank you for calling this to my attention. I'll probably also add diminished and augmented octaves now.
