### ISSUE TITLE
Key.primaryTriads missing augmented chords

### ISSUE THREAD

**Issue by brindy** [AudioKit/Tonic#6]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

`primaryTriads` on `Key` only contains major, minor and diminished triads, which is fine for major (Ionian) and natural minor (Aeolian) modes, but when using a different mode (e.g. Harmonic Minor, which is not an uncommon mode to use) the augmented triad is missing.

**For example:**
`Key(root: .C, scale: .harmonicMinor).primaryTriads`

**Expected:**
Cm, D°, **E♭⁺**, Fm, G, A♭, B°

**Actual:**
Cm, D°, Fm, G, A♭, B°

**Possible solution 1:**
Change `allowablePrimaryTriads` [Key.swift:45](https://github.com/AudioKit/Tonic/blob/main/Sources/Tonic/Key.swift#L45) to include `.augmentedTriad`.

The existing tests still pass when this is present.

**Possible solution 2:**
Add a function to `Key` that takes the allowable triad types and generates the full set of triads on the fly by duplicating a subset of the logic from `Key`'s init func, e.g. something like:

    public func triads(withTypes allowedTypes: [ChordType]) -> [Chord] {
        var triads: [Chord] = []
        for chord in chords where chord.noteClassSet.isSubset(of: noteSet.noteClassSet) {
            if allowedTypes.contains(chord.type) {
                triads.append(Chord(chord.root, type: chord.type))
            }
        }

        let triadsStartingWithC = triads.sorted(by: { $0.root.letter < $1.root.letter })
        let rootPosition = triadsStartingWithC.firstIndex(where: { $0.root == root }) ?? 0
        return Array(triadsStartingWithC.rotatingLeft(positions: rootPosition))
    }

Clients can also add this function as an extension in their own code base, though they would have to implement/copy the `rotatingLeft` func of `RangeReplaceableCollection` extension themselves.

**Possible solution: 3**
Make `ChordTable` public and allow it to be constructed with the allowed triads and accidentals for generating chords. This will allow clients to make an extension function, like in possible solution 2, with more precision:

`init(allowedTriadTypes: [ChordType], allowedAccidentals: [Accidental])`

**Comment by brindy** [comment]
Thanks for merging, @aure.

I'm also having a problem with missing double flat and double sharp triads.  One solution would be to simply add `.doubleFlat` and `.doubleSharp` to the accidentals list here: https://github.com/AudioKit/Tonic/blob/main/Sources/Tonic/ChordTable.swift#L18

Again, this doesn't break the existing tests.

However this swells the number of number of generated chords from 602 to 823.  It doesn't appear to have any impact on performance or memory though, so maybe it's not an issue.

What do you think?  Should I open another PR/issue for that?

Thanks in advance!

**Comment by aure** [comment]
If I recall correctly, I believe I restrict the accidentals because I never want to spell a chord that has triple accidentals like say C## augmented would require. Starting only from single accidentals prevents this. I welcome your thoughts for your use case though, so educate me.

**Comment by brindy** [comment]
My use case is to display all the triads for a list of scales/modes to aid with song writing.  So if the user chooses a key like Db major then I take the note (Db) and show other scales/modes too. This does result in some "theoretical" scales (like Db Phrygian) which includes double flats, but for completeness I want them to be there.

e.g. 

        let root = key.root
        let phrygianTriads = Key(root: root, scale: .phrygian).primaryTriads

This is a prototype of the UI, you can see the gaps where the double flats would be.

![Simulator Screen Shot - iPhone 13 mini - 2022-11-01 at 11 39 30](https://user-images.githubusercontent.com/81197/199224761-ecb9d3ca-42e6-4b28-bfa5-162d17b1089d.png)

I understand if you don't want to make that change.  What about my 3rd possible solution above?  This change would be none-breaking (the shared var would be configured as it is now), but it would allow clients to create their own chord tables more precisely.  I'm happy to create a PR with that change.

**Comment by aure** [comment]
I think it should be fine so long as you don't also expect to spell these chords since we don't support beyond double-accidentals.

**Comment by brindy** [comment]
That works for me, thanks.   

So next steps, do you want me to do anything?

**Comment by aure** [comment]
If you want to make a trivial PR for it, you should.

**Comment by brindy** [comment]
Will do, thanks!
